fixed depricated
Fix for this error
mongoose: ^v.5
(node:22828) DeprecationWarning: collection.update is deprecated. Use updateOne, updateMany, or bulkWrite instead.
(node:22828) UnhandledPromiseRejectionWarning: Error: Error saving autoref: modelForCurrentDoc.schema._getVirtual is not a function (doc 15)[object Object]